export const GET_TRANS_REQUEST = "GET_TRANS_REQUEST";
export const GET_TRANS_SUCCESS = "GET_TRANS_SUCCESS";
export const GET_TRANS_FAIL = "GET_TRANS_FAIL";

export const CREATE_TRANS_REQUEST = "CREATE_TRANS_REQUEST";
export const CREATE_TRANS_SUCCESS = "CREATE_TRANS_SUCCESS";
export const CREATE_TRANS_RESET = "CREATE_TRANS_RESET";
export const CREATE_TRANS_FAIL = "CREATE_TRANS_FAIL";

export const UPDATE_TRANS_REQUEST = "UPDATE_TRANS_REQUEST";
export const UPDATE_TRANS_SUCCESS = "UPDATE_TRANS_SUCCESS";
export const UPDATE_TRANS_RESET = "UPDATE_TRANS_RESET";
export const UPDATE_TRANS_FAIL = "UPDATE_TRANS_FAIL";

export const DELETE_TRANS_REQUEST = "DELETE_TRANS_REQUEST";
export const DELETE_TRANS_SUCCESS = "DELETE_TRANS_SUCCESS";
export const DELETE_TRANS_RESET = "DELETE_TRANS_RESET";
export const DELETE_TRANS_FAIL = "DELETE_TRANS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
